---
- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_os_family

- name: install on Debian based distros
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  loop: "{{ base_package }}"
  when: ansible_os_family == 'Debian'

- name: install on RHEL based distros
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  loop: "{{ base_package }}"
  when: ansible_os_family == 'RedHat'

- name: install on RHEL based distros
  dnf:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  loop: "{{ base_package }}"
  when: ansible_os_family == 'Fedora'
