---
- name: 'Include OS Family Specific Variables'
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - 'vars'

- include_tasks:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "install/{{ ansible_pkg_mgr }}.yml"
